import { useState } from 'react';
import { motion } from 'framer-motion';
import {
  X, Wrench, TriangleAlert, FileSpreadsheet, Layers, Boxes, BarChart3,
  ShieldCheck, ArrowRight, CircleCheck, CircleAlert,
} from 'lucide-react';
import type { Dataset, Histogram as Hist, DataModelTable } from '@/types';
import { int, pct, usdShort } from '@/utils/format';

/**
 * Data-integrity & engineering panel.
 *
 * Four tabs, all generated by the Medallion pipeline so nothing here can drift
 * out of step with the data: the corrections & limitations, the ETL layers, the
 * star schema, and the profiling. Built for a BI/DE portfolio — it shows how the
 * numbers were engineered, not just what they are.
 */

type Tab = 'integrity' | 'pipeline' | 'model' | 'profile';

export function DataNotesPanel({ ds, onClose }: { ds: Dataset; onClose: () => void }) {
  const { quality, meta, pipeline } = ds;
  const [tab, setTab] = useState<Tab>('integrity');

  const tabs: { id: Tab; label: string; icon: typeof Wrench }[] = [
    { id: 'integrity', label: 'Integrity', icon: ShieldCheck },
    ...(pipeline
      ? ([
          { id: 'pipeline', label: 'ETL', icon: Layers },
          { id: 'model', label: 'Data model', icon: Boxes },
          { id: 'profile', label: 'Profiling', icon: BarChart3 },
        ] as { id: Tab; label: string; icon: typeof Wrench }[])
      : []),
  ];

  return (
    <>
      <motion.div
        className="drawer__scrim"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.18 }}
        onClick={onClose}
      />
      <motion.aside
        className="drawer drawer--wide"
        role="dialog"
        aria-label="Data integrity and engineering notes"
        initial={{ x: '100%' }}
        animate={{ x: 0 }}
        exit={{ x: '100%' }}
        transition={{ duration: 0.28, ease: [0.2, 0, 0.1, 1] }}
      >
        <header className="drawer__head">
          <div>
            <p className="label">Data integrity &amp; engineering</p>
            <h2 className="drawer__title">How this dataset was built</h2>
          </div>
          <button type="button" className="btn btn--icon" onClick={onClose} aria-label="Close">
            <X size={16} />
          </button>
        </header>

        <nav className="drawer__tabs" role="tablist">
          {tabs.map((t) => {
            const Icon = t.icon;
            return (
              <button
                key={t.id}
                type="button"
                role="tab"
                aria-selected={tab === t.id}
                className={`drawer__tab ${tab === t.id ? 'is-active' : ''}`}
                onClick={() => setTab(t.id)}
              >
                <Icon size={13} aria-hidden />
                {t.label}
              </button>
            );
          })}
        </nav>

        <div className="drawer__body">
          {tab === 'integrity' ? <IntegrityTab ds={ds} /> : null}
          {tab === 'pipeline' && pipeline ? <PipelineTab ds={ds} /> : null}
          {tab === 'model' && pipeline ? <ModelTab model={pipeline.dataModel} /> : null}
          {tab === 'profile' && pipeline ? <ProfileTab profiling={pipeline.profiling} /> : null}
        </div>
        <span className="notes__buildstamp">
          Built {new Date(meta.generatedAt).toLocaleString()} · {quality.source}
        </span>
      </motion.aside>
    </>
  );
}

/* --------------------------------------------------------------- integrity */

function IntegrityTab({ ds }: { ds: Dataset }) {
  const { quality } = ds;
  return (
    <>
      <section className="notes__source">
        <FileSpreadsheet size={14} aria-hidden />
        <div>
          <p className="notes__file">{quality.source}</p>
          <p className="notes__meta">
            Sheets: {quality.sheets.join(', ')} · {int(quality.rowsRead)} rows read ·{' '}
            {int(quality.rowsKept)} kept
          </p>
        </div>
      </section>

      <section className="notes__group">
        <h3 className="notes__h">
          <Wrench size={13} aria-hidden />
          Corrections applied on import
        </h3>
        <p className="notes__lede">
          Changes the pipeline made to the workbook. Every figure in the dashboard reflects them.
        </p>
        <ul className="notes__list">
          {quality.corrections.map((c) => (
            <li key={c.id} className="note">
              <div className="note__head">
                <span className="note__id num">{c.id}</span>
                <span className="note__label">{c.label}</span>
                {typeof c.rows === 'number' ? (
                  <span className="note__rows num">
                    {int(c.rows)} {c.rows === 1 ? 'row' : 'rows'}
                  </span>
                ) : null}
              </div>
              <p className="note__detail">{c.detail}</p>
            </li>
          ))}
        </ul>
      </section>

      <section className="notes__group">
        <h3 className="notes__h">
          <TriangleAlert size={13} aria-hidden />
          What the workbook cannot support
        </h3>
        <p className="notes__lede">
          Questions with no answer in this data. Nothing in the dashboard estimates around them.
        </p>
        <ul className="notes__list">
          {quality.limitations.map((l) => (
            <li key={l.id} className="note note--limit">
              <div className="note__head">
                <span className="note__label">{l.label}</span>
              </div>
              <p className="note__detail">{l.detail}</p>
            </li>
          ))}
        </ul>
      </section>

      <section className="notes__group">
        <h3 className="notes__h">Field dictionary</h3>
        <dl className="notes__dict">
          {Object.entries(quality.fieldNotes).map(([field, note]) => (
            <div key={field} className="notes__dict-row">
              <dt>{field}</dt>
              <dd>{note}</dd>
            </div>
          ))}
        </dl>
      </section>
    </>
  );
}

/* ---------------------------------------------------------------- pipeline */

const LAYER_TONE: Record<string, string> = { Bronze: '#b06a2c', Silver: '#8a8f9c', Gold: '#c79a1e' };

function PipelineTab({ ds }: { ds: Dataset }) {
  const p = ds.pipeline!;
  return (
    <>
      <section className="notes__group">
        <h3 className="notes__h">
          <Layers size={13} aria-hidden />
          Medallion architecture
        </h3>
        <p className="notes__lede">
          A pandas ETL: raw → cleaned → star schema. The dashboard is built from the Gold layer,
          so the pipeline is the single source of truth.
        </p>

        <div className="lineage">
          {p.lineage.map((stage, i) => (
            <span key={stage} className="lineage__node">
              <span className="lineage__dot" />
              {stage}
              {i < p.lineage.length - 1 ? <ArrowRight size={11} className="lineage__arrow" /> : null}
            </span>
          ))}
        </div>

        <div className="etl">
          {p.etl.map((s) => (
            <div key={s.layer} className="etl__step">
              <div className="etl__badge" style={{ background: LAYER_TONE[s.layer] ?? 'var(--c-accent)' }}>
                {s.layer}
              </div>
              <div className="etl__body">
                <p className="etl__title">{s.title}</p>
                <p className="etl__detail">{s.detail}</p>
                <p className="etl__io num">
                  {int(s.rows_in)} <ArrowRight size={10} /> {int(s.rows_out)} rows ·{' '}
                  <code>{s.output}</code>
                </p>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="notes__group">
        <h3 className="notes__h">
          <ShieldCheck size={13} aria-hidden />
          Reconciliation &amp; quality gate
        </h3>
        <p className="notes__lede">
          Automated checks the build must pass. Totals tie out to{' '}
          <strong className="num">{usdShort(p.reconciliation.totals.sales_total)}</strong> sales and{' '}
          <strong className="num">{usdShort(p.reconciliation.totals.profit_total)}</strong> profit.
        </p>
        <ul className="checks">
          {p.reconciliation.checks.map((c) => (
            <li key={c.name} className={`check ${c.passed ? 'check--ok' : 'check--fail'}`}>
              {c.passed ? <CircleCheck size={15} aria-hidden /> : <CircleAlert size={15} aria-hidden />}
              <div>
                <p className="check__name">{c.name}</p>
                <p className="check__detail">{c.detail}</p>
              </div>
            </li>
          ))}
        </ul>
      </section>
    </>
  );
}

/* ------------------------------------------------------------------- model */

function ModelTab({ model }: { model: NonNullable<Dataset['pipeline']>['dataModel'] }) {
  return (
    <>
      <section className="notes__group">
        <h3 className="notes__h">
          <Boxes size={13} aria-hidden />
          Star schema
        </h3>
        <p className="notes__lede">
          Kimball star at <strong>{model.grain}</strong> grain — one fact, {model.dimensions.length}{' '}
          conformed dimensions. The order number is a degenerate dimension on the fact.
        </p>
        <StarDiagram model={model} />
      </section>

      <section className="notes__group">
        <h3 className="notes__h">Tables</h3>
        <div className="tbls">
          <TableCard t={model.fact} kind="fact" />
          {model.dimensions.map((d) => (
            <TableCard key={d.name} t={d} kind="dim" />
          ))}
        </div>
      </section>
    </>
  );
}

function TableCard({ t, kind }: { t: DataModelTable; kind: 'fact' | 'dim' }) {
  return (
    <div className={`tbl tbl--${kind}`}>
      <div className="tbl__head">
        <span className="tbl__name num">{t.name}</span>
        <span className="tbl__rows num">{int(t.rows)}</span>
      </div>
      <p className="tbl__grain">grain: {t.grain}</p>
      <div className="tbl__cols">
        {t.columns.map((c) => {
          const isKey = c.endsWith('_key');
          const isMeasure = t.measures?.includes(c);
          return (
            <span
              key={c}
              className={`tbl__col ${isKey ? 'is-key' : ''} ${isMeasure ? 'is-measure' : ''}`}
            >
              {c}
            </span>
          );
        })}
      </div>
      {t.note ? <p className="tbl__note">{t.note}</p> : null}
    </div>
  );
}

function StarDiagram({ model }: { model: NonNullable<Dataset['pipeline']>['dataModel'] }) {
  const W = 440;
  const H = 320;
  const cx = W / 2;
  const cy = H / 2;
  const dims = model.dimensions;
  const R = 118;
  const nodes = dims.map((d, i) => {
    const a = (i / dims.length) * Math.PI * 2 - Math.PI / 2;
    return { d, x: cx + Math.cos(a) * R, y: cy + Math.sin(a) * R };
  });
  return (
    <div className="star">
      <svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Star schema diagram" className="star__svg">
        {nodes.map((n) => (
          <line key={`l-${n.d.name}`} x1={cx} y1={cy} x2={n.x} y2={n.y} className="star__link" />
        ))}
        {nodes.map((n) => (
          <g key={n.d.name} transform={`translate(${n.x},${n.y})`}>
            <rect x={-52} y={-15} width={104} height={30} rx={7} className="star__dim" />
            <text y={-2} className="star__dim-name">{n.d.name}</text>
            <text y={9} className="star__dim-rows">{int(n.d.rows)} rows</text>
          </g>
        ))}
        <g transform={`translate(${cx},${cy})`}>
          <rect x={-58} y={-22} width={116} height={44} rx={9} className="star__fact" />
          <text y={-4} className="star__fact-name">{model.fact.name}</text>
          <text y={11} className="star__fact-rows">{int(model.fact.rows)} rows</text>
        </g>
      </svg>
    </div>
  );
}

/* ----------------------------------------------------------------- profile */

const MEASURE_LABEL: Record<string, string> = {
  sales: 'Sales ($)', profit: 'Profit ($)', discount: 'Discount', quantity: 'Quantity',
  base_margin: 'Base margin',
};

function ProfileTab({ profiling }: { profiling: NonNullable<Dataset['pipeline']>['profiling'] }) {
  const measures = Object.keys(profiling.summary);
  return (
    <>
      <section className="notes__group">
        <h3 className="notes__h">
          <BarChart3 size={13} aria-hidden />
          Summary statistics
        </h3>
        <div className="stats__scroll">
          <table className="stats">
            <thead>
              <tr>
                <th>Measure</th><th className="n">Mean</th><th className="n">Median</th>
                <th className="n">P25</th><th className="n">P75</th>
                <th className="n">Min</th><th className="n">Max</th>
              </tr>
            </thead>
            <tbody>
              {measures.map((m) => {
                const s = profiling.summary[m];
                const money = m === 'sales' || m === 'profit';
                const f = (v: number) =>
                  m === 'discount' || m === 'base_margin' ? pct(v, money ? 0 : 1) : money ? usdShort(v) : int(v);
                return (
                  <tr key={m}>
                    <th scope="row">{MEASURE_LABEL[m] ?? m}</th>
                    <td className="n num">{f(s.mean)}</td>
                    <td className="n num">{f(s.median)}</td>
                    <td className="n num">{f(s.p25)}</td>
                    <td className="n num">{f(s.p75)}</td>
                    <td className="n num">{f(s.min)}</td>
                    <td className="n num">{f(s.max)}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </section>

      <section className="notes__group">
        <h3 className="notes__h">Distributions</h3>
        <div className="hists">
          {profiling.histograms.map((h) => (
            <HistogramChart key={h.id} h={h} />
          ))}
        </div>
      </section>
    </>
  );
}

function HistogramChart({ h }: { h: Hist }) {
  const W = 200;
  const H = 84;
  const pad = 2;
  const n = h.counts.length;
  const max = Math.max(1, ...h.counts);
  const bw = (W - pad * 2) / n;
  return (
    <figure className="hist">
      <figcaption className="hist__title">{h.title}</figcaption>
      <svg viewBox={`0 0 ${W} ${H}`} className="hist__svg" role="img" aria-label={h.title}>
        {h.counts.map((c, i) => {
          const bh = (c / max) * (H - 16);
          const mid = h.edges ? (h.edges[i] + h.edges[i + 1]) / 2 : 0;
          const neg = h.diverging && mid < 0;
          return (
            <rect
              key={i}
              x={pad + i * bw}
              y={H - 12 - bh}
              width={Math.max(0.6, bw - 0.8)}
              height={bh}
              className={`hist__bar ${neg ? 'hist__bar--neg' : ''}`}
            />
          );
        })}
      </svg>
      <div className="hist__axis num">
        <span>{h.kind === 'bar' ? h.labels?.[0] : fmtEdge(h.edges?.[0], h.unit)}</span>
        <span>{h.kind === 'bar' ? h.labels?.[n - 1] : fmtEdge(h.edges?.[n], h.unit)}</span>
      </div>
    </figure>
  );
}

function fmtEdge(v: number | undefined, unit: string): string {
  if (v === undefined) return '';
  if (unit === '$') return usdShort(v);
  if (unit === '%') return `${v}%`;
  return int(v);
}
