import { motion } from 'framer-motion';
import { X, Wrench, TriangleAlert, FileSpreadsheet } from 'lucide-react';
import type { Dataset } from '@/types';
import { int } from '@/utils/format';

/**
 * Data integrity panel.
 *
 * Two lists, kept distinct: corrections are changes this app made to the
 * workbook on import, and limitations are questions the workbook cannot answer
 * at all. Both are generated by the ETL, so this panel cannot drift out of step
 * with what the pipeline actually did.
 */
export function DataNotesPanel({ ds, onClose }: { ds: Dataset; onClose: () => void }) {
  const { quality, meta } = ds;

  return (
    <>
      <motion.div
        className="drawer__scrim"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.18 }}
        onClick={onClose}
      />
      <motion.aside
        className="drawer"
        role="dialog"
        aria-label="Data integrity notes"
        initial={{ x: '100%' }}
        animate={{ x: 0 }}
        exit={{ x: '100%' }}
        transition={{ duration: 0.28, ease: [0.2, 0, 0.1, 1] }}
      >
        <header className="drawer__head">
          <div>
            <p className="label">Data integrity</p>
            <h2 className="drawer__title">What this dataset can and cannot say</h2>
          </div>
          <button type="button" className="btn btn--icon" onClick={onClose} aria-label="Close">
            <X size={16} />
          </button>
        </header>

        <div className="drawer__body">
          <section className="notes__source">
            <FileSpreadsheet size={14} aria-hidden />
            <div>
              <p className="notes__file">{quality.source}</p>
              <p className="notes__meta">
                Sheets: {quality.sheets.join(', ')} · {int(quality.rowsRead)} rows read ·{' '}
                {int(quality.rowsKept)} kept · built {new Date(meta.generatedAt).toLocaleString()}
              </p>
            </div>
          </section>

          <section className="notes__group">
            <h3 className="notes__h">
              <Wrench size={13} aria-hidden />
              Corrections applied on import
            </h3>
            <p className="notes__lede">
              Changes this pipeline made to the workbook. Every figure in the dashboard reflects
              them.
            </p>
            <ul className="notes__list">
              {quality.corrections.map((c) => (
                <li key={c.id} className="note">
                  <div className="note__head">
                    <span className="note__id num">{c.id}</span>
                    <span className="note__label">{c.label}</span>
                    {typeof c.rows === 'number' ? (
                      <span className="note__rows num">
                        {int(c.rows)} {c.rows === 1 ? 'row' : 'rows'}
                      </span>
                    ) : null}
                  </div>
                  <p className="note__detail">{c.detail}</p>
                </li>
              ))}
            </ul>
          </section>

          <section className="notes__group">
            <h3 className="notes__h">
              <TriangleAlert size={13} aria-hidden />
              What the workbook cannot support
            </h3>
            <p className="notes__lede">
              Questions with no answer in this data. Nothing in the dashboard estimates around
              them.
            </p>
            <ul className="notes__list">
              {quality.limitations.map((l) => (
                <li key={l.id} className="note note--limit">
                  <div className="note__head">
                    <span className="note__label">{l.label}</span>
                  </div>
                  <p className="note__detail">{l.detail}</p>
                </li>
              ))}
            </ul>
          </section>

          <section className="notes__group">
            <h3 className="notes__h">Field dictionary</h3>
            <dl className="notes__dict">
              {Object.entries(quality.fieldNotes).map(([field, note]) => (
                <div key={field} className="notes__dict-row">
                  <dt>{field}</dt>
                  <dd>{note}</dd>
                </div>
              ))}
            </dl>
          </section>
        </div>
      </motion.aside>
    </>
  );
}
